services:
  - type: web
    name: line-chatgpt-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: LINE_ACCESS_TOKEN
        sync: false
      - key: LINE_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
